### ISSUE TITLE
ERROR: None (while there is an error)

### ISSUE THREAD

**Issue by job** [irrdnet/irrd#297]
**Describe the bug**
When a user attempts to submit multiple instructions to the daemon, for instance:

```
override: XYZ

route: 10.0.0.0/24
[snip]
origin: AS123
delete: not needed
 
route: 10.0.1.0/24
[snip]
origin: AS123
delete: not needed
```

Notice the ` ` on what is supposed to be a double newline separation between the two records. Instead of `^$` the objects are separated by newlines and something that matches `^ $` - hope this is clear enough.

The user then gets back:

```
Subject: ERROR: None
Date: Thu, 16 Apr 2020 21:23:32 +0000 (UTC)
Unfortunately, your message with ID <20200416212331.GA89550@shrubbery.net>
could not be processed, due to an internal error.    
------------------------------------------------------------
The NTT Global IP Network Routing Registry is
operated by db-admin@rr.ntt.net.  Whois queries   
to rr.ntt.net (primary) or rr1.ntt.net (backup).   
see https://www.gin.ntt.net/support/policy/rr.cfm for more information.
Generated by IRRd version 4.0.8 on irrd01
```

The IRRd instance had understood the blob to be a single (obviously) invalid object. This is fine and expected.

What is somewhat curious here is that the user is notified `ERROR: None`, and that the internal error does not give a lot of guidance on what exactly could've gone wrong. Is it possible to expose more traceback information to the user so they can understand the error better?

**Comment by haussli** [comment]
The log had this:
Message: 'An exception occurred while attempting to process the following update: <e-mail removed> --- traceback for Parsing of 213.198.94.152/29 reads 213.198.94.152 for ip_first,but value 204.245.208.192 is already set. follows:'

**Comment by mxsasha** [comment]
This is definitely a bug in the parser. The object (as it is a single object) should be rejected as any other kind of invalid object submission.

The limited content in the email is intentional. If during email processing, an unexpected exception occurs, processing of the entire email is ended, the user gets a generic error message, and more information is in the log file. This ensures privileged information does not leak out through replies to the user. The same happens if the database couldn't be contacted, for example. The same also happens for whois queries. So this part is intentional behaviour, though the `Error: None` subject is not pretty.

I'll look into the subject and the parser bug.

**Comment by job** [comment]
Thanks!
