### ISSUE TITLE
Hide mirrored & reject authoritative objects based on selection criteria

### ISSUE THREAD

**Issue by job** [irrdnet/irrd#4]
We'll need the ability to hide objects coming in over NRTM, and reject objects slated for insertion in the authoritative database based on selection criteria such as:

* Is the prefix a covered by a list of bogon prefixes? (aka ability to ignore rfc1918 space)
* Is the origin ASN a member of the list of bogon ASNs? (ignore route objects originated by private or special ASNs such as 23456)

**Comment by job** [comment]
I should clarify:

For `route/route6:` objects I want to be able to block certain objects from being considered if the prefix or the origin ASN matches against a blocklist.

For `route-set` objects I want to be able to block objects from being considered if any of the member prefixes matches a blocklist of prefixes (or covering prefixes).

For `as-set` objects I want to be able to block objects if any of the members matches against a blocklist of ASNs (usually a range).

**Comment by mxsasha** [comment]
@job So, to clarify, the full implementation of this would be:

Object rejection:
- The operator defines a set of blocked (rejected? bogon? we need to settle on a term) prefixes and ASNs or ASN ranges. This set applies to the entire IRRd instance, except specifically excluded sources.
- A route(6) object is rejected if the origin is in the blocklist, or the prefix overlaps with any blocked prefix (i.e. the route(6) prefix is a more specific or less specific of a blocked prefix)
- A route-set object is rejected if any of the direct members (no recursion) overlaps with any blocked prefix (more or less specific)
- An as-set object is rejected if any of the members are blocked ASNs
- Other object classes are never rejected

If an object is rejected:
- Creation of a the object in an authoritative database will fail
- Changing the object in an authoritative database is permitted (it seems crude to force an as-set to be deleted and recreated, when the only thing needed is to remove one blocked AS)
- Deleting the object in an authoritative database is permitted
- If it is received over NRTM, it will not be recorded in the local journal, i.e. mirrors from an IRRd with blocklist will not see rejected objects
- Rejected objects are never included in exports
- Rejected objects are never included in any query responses. We can add a !f flag to disable this behaviour for some queries as a debugging aid.
- If an object changes between rejected and not rejected, it will become (in)visible to query responses, and an NRTM ADD or DEL will be added to the journal, so that mirrors follow this state. This is much more rare with this feature than with RPKI, but may still happen when settings are changed, or when initially enabling object rejection.

Is this correct and are we missing anything? We do need to settle on a good term for this behaviour.

**Comment by job** [comment]
looks good to me! thanks

**Comment by job** [comment]
name: "Out of Scope" objects, with "scope filters"... for lack of better wording for now :)

**Comment by mxsasha** [comment]
I ran some testing filtering out anything from the IANA special usage lists for IPv4/IPv6/ASN. Here's what the numbers of invalid objects that would no longer be visible look like - about 3000 objects total:
```
irrd=# select source, count(*) from rpsl_objects where scopefilter_status<>'in_scope' group by source;
    source    | count 
--------------+-------
 AFRINIC      |     4
 ALTDB        |    38
 APNIC        |    41
 ARIN         |   924
 ARIN-NONAUTH |    21
 BBOI         |     1
 BELL         |     5
 JPIRR        |     7
 LEVEL3       |   125
 NTTCOM       |   142
 RADB         |  1421
 RIPE         |   364
 RIPE-NONAUTH |    67
 TC           |     2
(14 rows)

irrd=# select object_class, count(*) from rpsl_objects where scopefilter_status<>'in_scope' group by object_class;
 object_class | count 
--------------+-------
 as-set       |   616
 aut-num      |    11
 route        |  2280
 route-set    |   155
 route6       |   100
(5 rows)
```

**Comment by mxsasha** [comment]
I ran some testing filtering out anything from the IANA special usage lists for IPv4/IPv6/ASN. Here's what the numbers of invalid objects that would no longer be visible look like - about 3000 objects total, and this should give some indication of the impact of enabling this in the way I did:

```
irrd=# select source, count(*) from rpsl_objects where scopefilter_status<>'in_scope' group by source;
    source    | count 
--------------+-------
 AFRINIC      |     3
 ALTDB        |    37
 APNIC        |    34
 ARIN         |   922
 ARIN-NONAUTH |    21
 BBOI         |     1
 BELL         |     5
 JPIRR        |     5
 LEVEL3       |   114
 NTTCOM       |   141
 RADB         |  1409
 RIPE         |   348
 RIPE-NONAUTH |    67
 RPKI         |    80
 TC           |     2
(15 rows)

irrd=# select object_class, count(*) from rpsl_objects where scopefilter_status<>'in_scope' group by object_class;
 object_class | count 
--------------+-------
 as-set       |   578
 aut-num      |    11
 route        |  2355
 route-set    |   140
 route6       |   105
(5 rows)
```

The 80 out of scope objects for RPKI are ROAs with a private ASN or 23456 as their origin.

Out of scope route(6) objects per source:
```
irrd=# select source, count(*) from rpsl_objects where scopefilter_status<>'in_scope' and (object_class='route' or object_class='route6') group by source;
    source    | count 
--------------+-------
 ALTDB        |    30
 APNIC        |     4
 ARIN         |   897
 ARIN-NONAUTH |    19
 BBOI         |     1
 BELL         |     5
 JPIRR        |     1
 LEVEL3       |    42
 NTTCOM       |   133
 RADB         |  1182
 RIPE-NONAUTH |    66
 RPKI         |    80
(12 rows)
```

A lot of the out of scope route objects are also from just a few maintainers:
```
irrd=# select parsed_data->'mnt-by' as mntner, count(*) as count from rpsl_objects where scopefilter_status<>'in_scope' and object_class='route' group by mntner order by count desc limit 25;
        mntner        | count 
----------------------+-------
 ["MNT-VINAK-4"]      |   887
 ["INAP-MAINT-RADB"]  |   375
 ["MAINT-AS2764"]     |   366
 ["MAINT-AS9304"]     |    82
                      |    75
.....
 ```

For NTTCOM specifically (all classes), it's also just a handful of mntners:
```
irrd=# select parsed_data->'mnt-by' as mntner, count(*) as count from rpsl_objects where scopefilter_status<>'in_scope' and source='NTTCOM' group by mntner order by count desc limit 25;
        mntner         | count 
-----------------------+-------
 ["MAINT-AS9304"]      |    76
 ["MAINT-EQUINIXPAC"]  |    24
 ["MAINT-EQUINIXSGW"]  |     9
....
```

For out of scope as-sets:
```
irrd=# select parsed_data->'mnt-by' as mntner, count(*) as count from rpsl_objects where scopefilter_status<>'in_scope' and object_class='as-set' group by mntner order by count desc limit 25;
        mntner         | count 
-----------------------+-------
 ["DECIX-MNT"]         |    35
 ["MAINT-THIX-CAT-TH"] |    33
 ["INAP-MAINT-RADB"]   |    15
......
```

The DE-CIX one seem to include as-sets for route servers like AS-DECIX-DUS-RS, as they have members with a private AS. **These objects "disappearing" might cause operational impact for some people?**

For out of scope route sets:
```
irrd=# select parsed_data->'mnt-by' as mntner, count(*) as count from rpsl_objects where scopefilter_status<>'in_scope' and object_class='route-set' group by mntner order by count desc limit 25;
           mntner            | count 
-----------------------------+-------
 ["LEVEL3-MNT"]              |    25
 ["MAINT-AS11537"]           |     9
 ["MAINT-AS7545"]            |     4
......
```

**Comment by job** [comment]
@mxsasha is it easy for you to generate a text file with all the 'out of scope' objects in RPSL format?

**Comment by job** [comment]
small nit: `AS 112`, `2620:4f:8000::/48`, `192.175.48.0/24` should not be part of this scope filter.

**Comment by mxsasha** [comment]
> small nit: `AS 112`, `2620:4f:8000::/48`, `192.175.48.0/24` should not be part of this scope filter.

Yes, I kinda just picked a list from the IANA special use lists. This isn't the default config - just the config I used when I generated those files :)

**Comment by job** [comment]
upon second thought, we probably should not apply scope filters to `route-set` objects

**Comment by mxsasha** [comment]
Update on offline decision: the filtering in sets isn't very practical. Filtering in any context will only be done for `route` and `route6`, for the route and origin attributes.
