### ISSUE TITLE
Consider adding "Legacy WHOISoHTTPS" query API

### ISSUE THREAD

**Issue by job** [irrdnet/irrd#410]
I asked around for feedback on GraphQL as the new query language, and an interesting suggestion came up in talks with Jared Mauch.

There is a group of people who are perfectly happy with the 'simple port 43' query language (`!a`, `!g`, etc), but who would definitely benefit from the ability to wrap the commands send with `netcat` into a `curl` equivalent with minimal effort.

Perhaps we can consider to have a "HTTPS to port 43" bridge for singleton queries leveraging the existing code, in addition to the GraphQL-style API for advanced queries?

**Comment by mahtin** [comment]
The idea of layering the protocol support and then focus solely on GraphQL as the primary interface is a solid idea.

If the whois-to-GraphQL module is written as a fully standalone project (as it could be), then it could be used for others purposes.

Another plus could be that as whois is deprecated (one can only hope!) that the core software isn't encumbered with cruddy old port-43 logic. 

PS: RDAP is the new whois, so an RDAP-to-GraphQL module would be on the books at some point.

**Comment by mxsasha** [comment]
> There is a group of people who are perfectly happy with the 'simple port 43' query language (`!a`, `!g`, etc), but who would definitely benefit from the ability to wrap the commands send with `netcat` into a `curl` equivalent with minimal effort.
> 
> Perhaps we can consider to have a "HTTPS to port 43" bridge for singleton queries leveraging the existing code, in addition to the GraphQL-style API for advanced queries?

We can do that. It's not ideal from the perspective of wanting to get people to use the newest and shiniest API, but it will help to get people away from plain-text unauthenticated whois queries.

There is a catch when supporting only a single query in a single HTTP request though: the latency is higher. It's not just the TCP connection setup, but also SSL and HTTP request handling. A possibility would be to offer three options:

- The new shiny flexible GraphQL API
- A simple HTTP call to execute a single query, getting the result back as text/plain. This would also not include the wrapping for IRRd queries with the number of bytes, and probably we should use normal HTTP codes instead of magic answers like `D` for not found. So simpler to parse, still closely compatible, but higher latency if you run a ton of queries.
- A multi-query HTTP call, very similar to the previous option, but where each result is wrapped in a JSON array, to distinguish the answers to each query in a reasonable HTTP-like manner. Reduces latency compared to one HTTP request per query, but is still quite close in compatibility.

However, by separating like this, we may be making it too granular and making too many interfaces. By offering more options, we may also end up lowering interest in the GraphQL - because while it will be much more flexible and adaptable than any other option, it has a slight learning curve.

(GraphQL already supports sending multiple queries in one request, and some cases where you'd run a lot of whois queries it can fit in a single GraphQL query, so the latency is not so much a concern there.)

**Comment by forkwhilefork** [comment]
Just to add a data point - I have never used GraphQL, and I would prefer to make a simple HTTP call (i.e. your second bullet) than to learn/use GraphQL.

**Comment by mxsasha** [comment]
See https://irrd.readthedocs.io/en/latest/users/queries/index.html and https://irrd.readthedocs.io/en/latest/users/queries/whois.html
