### ISSUE TITLE
IRR-Maint-tool to facilitate pushes to any IRR - Derived from IRRd

### ISSUE THREAD

**Issue by fischerdouglas** [irrdnet/irrd#414]
For an ITP, Keep IRR Objects correctly Up to date is a pain!
Even the basic as AS-Sets could be a challenge if you want to keep updated all you cone correctly.

I have been looking for a tool that can help with this task for a long time.
And the best I found was some Jinja2 Templates e-mail to IRR.
But that does not cover any type of checking beyond the RPSL syntax, and even those do not cover all the object types on RPSL-NG.

I was looking at the resources already in IRRd, and my first impression is that it already has all the basics(modeling, parsing, templating, and consistency checking) to an automagical IRR-Maint-Tool.

So I'm suggesting the possibility of a complementary tool, based mostly on the already existent code in IRRd, that would allow IRR Maintainers to automatically push Adds/Updates/Removes to any IRR to keep update all their objects...

My idea is a new "thing" that could be consumed (maybe an API or python directly) by some triggers on IPAM/DCIM like Peering-Manager ou NetBox.

P.S. I know that the official scope of IRRd is not to provide tools to Maintainers.
But I also know that the original motivation of this "refreshes" IRR Deamon is to avoid the creation of new incorrect IRR objects and help to clean-up the already existent incorrect IRR objects.
My line of reasoning was:
If we can help colleagues to maintain their objects in a more automated way, these databases will become more reliable.

**Comment by fischerdouglas** [comment]
Obs.:
After I knew IRRdv4(2 days ago), my first idea was a little more selfist.
- Create an internal IRR
- Insert the objects I need there(maybe using some triggers from PeeringManager)
- Use the Mirroring export feature to get the data already parsed, formated, checked.
- Send it to RADB and other IRRs...

Probably it would work but would be as pretty as my face...
So, by now I'm discarding this idea.

**Comment by mxsasha** [comment]
The RPSL parser in IRRd is pretty decent and is fairly self-contained. However, note that it doesn't do anything with the content of (mp-)import/export attributes, so it's not a full RPSL policy implementation.

More importantly, it only parses objects, and knows what objects look like. It doesn't currently have a generator for objects. But, a currently ongoing project is to explore a better way for people to submit RPSL objects instead of plaintext emails. Some kind of API, but beyond that there are no specs yet. This would be limited to working on IRRd instances, i.e. you can't use it to submit objects to RIPE, but it sounds like it overlaps a lot with your ideas. Do you have any ideas on what an ideal API for object submission would look like?

**Comment by fischerdouglas** [comment]
One of the possibilities that were considered between some friends for a while would be something that could be called:

A IRR API-to-RPSL-Mail Middleware.

Something that would do the needed parsing, render the RPSL, and push it to the respective IRR by e-mail.

Yep! I now! This does not fit with the basic concepts of a Deamon for IRR.

But I'm sure that making cost less and easier to ASN admins to push correct info to the IRRs, will meet the goal of a trustable IRR database in a few years.

**Comment by mxsasha** [comment]
I don't think the existing IRRd code can help a lot with this, and it's not within scope of IRRd itself. It also this may require customisation for different IRRs: not everyone has support for the same fields.
