### ISSUE TITLE
Delete route/route6 objects that are RPKI invalid

### ISSUE THREAD

**Issue by forkwhilefork** [irrdnet/irrd#427]
In #3, @job mentions this:

> RPKI data sources is expected to refresh every 30 - 60 minutes.
> 
> After the RPKI source refreshes, the authoritative database must be scanned and all conflicting objects must be deleted (also send deletes via NRTM, and send notification mails "this was deleted because of conflict with datasource X").

#3 was closed in favor of #197, which doesn't appear to include the functionality described above. I'd still like to see that.

**Comment by mxsasha** [comment]
This was not mentioned in #197, but was implemented - see https://irrd.readthedocs.io/en/stable/admins/rpki.html

Technically, they're not deletions, they are marked as RPKI invalid and therefore not visible in query output. This because the RPKI state might change again later, in which case we need to "restore" the object again, done by marking it as RPKI valid/not_found. As objects change between valid/not_found and invalid, NRTM DEL's and ADD's are generated.

Notifications are sent, but only for objects from authoritative sources, and only if the setting is enabled.

**Comment by forkwhilefork** [comment]
An object being RPKI invalid is an indicator that it may be stale and therefore should be removed or "cleaned-up", which is why I was interested in actual deletion. I think it probably doesn't make sense to delete by default, but it would be nice if there were at least some way to query for all the route/route6 objects that are currently invalid. Then further analysis and possibly deletion could be done. Is that supported currently?

**Comment by mxsasha** [comment]
Yes, you can query it in the GraphQL interface:
```
query {
  rpslObjects(rpkiStatus: invalid) {
    ... on RPSLRoute {
      rpslPk
    	prefix
      asn
      source
    }
    ... on RPSLRoute6 {
      rpslPk
    	prefix
      asn
      source
    }
  }
}
```
It's about 220.000 RPSL objects on my testing instance, so it's not a very fast query.

The whois interface does not have support for this.

**Comment by forkwhilefork** [comment]
Okay, this works. I will wait for the next release. Thanks!
