### ISSUE TITLE
deployment example with setcap does not work due to virtualenv symbolic links

### ISSUE THREAD

**Issue by ccaputo** [irrdnet/irrd#460]
**Describe the bug**

I'm finding that:

https://github.com/irrdnet/irrd/blob/05dde61726883bf3eb6d41432dc66b77b01702b2/docs/admins/deployment.rst#L287-L288

is not possible since in a virtualenv the python3 will be a symbolic link, and setcap does not work on symbolic links.

I am concerned that running setcap on the actual python3 binary would be a security risk since any python code could then take advantage of the elevated privs, plus this adds a burden of needing to remember to reconfigure the privs after any python upgrade.

With the move from twistd to irrd, would it be possible to have irrd open any needed privileged ports and then drop privileges?  Are there other ways to handle this besides IPtables forwarding?

**Comment by mxsasha** [comment]
I see your point, it's not a pretty setup. In 4.2 the recommendation (and default) is to bind the HTTP interface on a non-privileged port and use a frontend like nginx, so that part is taken care of.

Currently the only alternative for port 43 is indeed IPtables, but I will look into options to bind the port before dropping privileges, I think it would be a nice improvement.

**Comment by mxsasha** [comment]
@ccaputo I think https://github.com/irrdnet/irrd/blob/main/docs/admins/deployment.rst#starting-irrd solves this - IRRd can now be started as root, bind to port 43 and then drop root privileges.

**Comment by ccaputo** [comment]
Nice work!  Will try when 4.2 is out.  Thx.
