### ISSUE TITLE
Temporary files not cleaned up if IRRd import fails

### ISSUE THREAD

**Issue by mxsasha** [irrdnet/irrd#487]
It looks like IRRd may not be cleaning up temporary files if an IRR import fails. These files can be quite large, so this isn't nice, and probably not too hard to fix for the most common failure scenarios.

**Comment by mxsasha** [comment]
Digging up the original report, this was mainly about IRRd being killed rather than an exception occurring during import. This is rather difficult to resolve, files are already in an appropriate temporary directory, and are only large on full imports, which are fairly rare. Therefore, closing.

**Comment by MattKobayashi** [comment]
Hi @mxsasha, we ran into this issue recently, it caused Postgres to fail due to a lack of disk space. At what point are these temporary files safe to delete? I'm toying with the idea of using a cron job to delete the files that haven't been accessed in at least 24 hours, but I'm not sure how long they're actually needed by IRRd.
