### ISSUE TITLE
Can't NRTM mirror RIPE database, even though they support it

### ISSUE THREAD

**Issue by rubenskuhl** [irrdnet/irrd#494]
**Describe the bug**
Configuring NRTM hosts on RIPE doesn't work, but whois.ripe.net 4444 does support NRTM

**To Reproduce**
Configure the following source:
``` RIPE:
            authoritative: false
            keep_journal: true
            import_serial_source: 'https://ftp.ripe.net/ripe/dbase/RIPE.CURRENTSERIAL'
            import_source: 'https://ftp.ripe.net/ripe/dbase/ripe.db.gz'
            nrtm_host: whois.ripe.net
            nrtm_port: 4444
            rpki_excluded: true
            object_class_filter:
                - as-set
                - aut-num
                - filter-set
                - inet-rtr
                - key-cert
                - mntner
                - peering-set
                - route
                - route6
                - route-set
                - rtr-set
````

**Expected behaviour**
What was expected was NRTM to work, but instead:
Remote information:
    NRTM host: whois.ripe.net port 4444
    Remote status query unsupported or query failed

**IRRd version you are running**
4.2.0b1

**Additional context**
It seems that RIPE limitation of only allowing the last 14 days of serials on NRTM might be making IRRd NRTM test to fail. NRTM with recent enough starting serial numbers work. 

```telnet whois.ripe.net 4444
Trying 2001:67c:2e8:22::c100:687...
Connected to whois.ripe.net.
Escape character is '^]'.
% The RIPE Database is subject to Terms and Conditions.
% See http://www.ripe.net/db/support/db-terms-conditions.pdf

-g RIPE:3:11012700-LAST
%ERROR:401: (Requesting serials older than 14 days will be rejected)```

**Comment by rubenskuhl** [comment]
After being whitelisted by AFRINIC, I can reproduce the same error with them as well:
2021-04-21 14:15:53,417 irrd[2038142]: [irrd.mirroring.mirror_runners_import#DEBUG] Received NRTM response for AFRINIC: %ERROR:401: invalid range: Not within 1-1060647

But since RIPE doesn't require whitelisting, it's easier to reproduce with RIPE

**Comment by rubenskuhl** [comment]
Just adding a query showing that RIPE supports NRTM from that client IP address:
```
-q sources
RIPE:3:X:2278326-50703821
RIPE-NONAUTH:3:X:2278326-50703821
```

**Comment by rubenskuhl** [comment]
Any comments on this, @mxsasha ?

**Comment by mxsasha** [comment]
The message:

> Remote information:
> NRTM host: whois.ripe.net port 4444
> Remote status query unsupported or query failed

Is slightly confusing. It doesn't mean that NRTM is failing, it only means that the `!j` status query was not successful. It never will be, because RIPE (and other RIPE-based databases lik AFRINIC) do not support it.

This message:
> 2021-04-21 14:15:53,417 irrd[2038142]: [irrd.mirroring.mirror_runners_import#DEBUG] Received NRTM response for AFRINIC: %ERROR:401: invalid range: Not within 1-1060647

Is also somewhat misleading. I don't have the rest of your log, but I am assuming that your local IRRd was up to date with AFRINIC up to 1060646. IRRd has no reliable way of knowing whether or not 1060646 is still the latest serial, and the simplest way to check is to ask for 1060647-LAST. If there were newer updates, they are immediately returned, if not, the NRTM source returns an error. So seeing this error logged does not mean something actually broke.

The underlying issue here is:
* Serials in IRR are not always a well defined concept
* Information about available serials and error messages are different in different NRTM implementations

**Comment by rubenskuhl** [comment]
Any way to tell that an IRRd 4.2 depolyment is currently able to NRTM RIPE-like sources ?

**Comment by mxsasha** [comment]
You can see whether new changes are reflected. That's the only concept of "working" hat exists in NRTM. RIPE has fairly frequent changes, so you should see your local serial increasing, and also see updates to objects appear in the logs.
