### ISSUE TITLE
opt-out for as-set hierarchical name - just for legacy objects

### ISSUE THREAD

**Issue by fischerdouglas** [irrdnet/irrd#559]
**Is your feature request related to a problem? Please describe.**
If I understood correctly "compatibility.permit_non_hierarchical_as_set_name" exception was created to support legacy databases that are in process to migrate to IRRd4. IRR bases that until today supports non-hierarchical AS-SET names.

But is a fact that the hierachical as-set mas is a good Idea to avoid mistakes...
Especially considering relational Integrity checks against different databases.

**Describe the solution you'd like**
Have you considered the possibility of a compatibility atribute that allows only legacy objects, and block the creation of new AS-Set without hierarchical names?

Maybe something like
compatibility.permit_non_hierarchical_as_set_name_just_for_legacy_objects

It would not break what is already working, and it would prevent non-standard things from being created.

**Comment by mxsasha** [comment]
> Have you considered the possibility of a compatibility atribute that allows only legacy objects, and block the creation of new AS-Set without hierarchical names?

Yes. That is already the default. We allow updating existing objects, because you can't "update" the name of an as-set - a different primary key means you are creating a new one. It seemed too harsh to not allow a user to update their existing set because we have since then decided that the name is invalid. Particularly because the set name is referred by other objects and external configuration.

So the setting only changes the behaviour for creating new ones. I was already in discussion with one potential operator about more refined settings around name validation, but in general, stricter validation requirements may make some operators more reluctant to upgrade to newer versions, and I want to avoid that.

I would like to apply really strict rules to create very neat registries, but it's the operator's choice, and their customers that they need to explain things to. And more important to me than RPSL neatness is that everyone runs the latest version as much as possible, which means making upgrades possible for all users. People staying stuck on old versions will be much worse for RPSL innovation than some registries having a bit more lax validation rules.
