### ISSUE TITLE
Upgrade from 4.2.0b1 to 4.2.0 release doesn't work

### ISSUE THREAD

**Issue by rubenskuhl** [irrdnet/irrd#563]
**Describe the bug**
Upgrading from 4.2.0b1 to 4.2.0 release doesn't work

**To Reproduce**
Install 4.2.0b1, then upgrade, run irrd_database_upgrade and then start 4.2.0

**Expected behaviour**
Upgrading to work

**IRRd version you are running**
4.2.0b1, 4.2.0

**Additional context**
It seems the problem is in database configurations:
"sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  role "root" does not exist"

**Comment by mxsasha** [comment]
I think something else is happening here. I'm guessing that your database_url is configured so that PostgreSQL connects over a unix socket using peer authentication, and you are running the database_upgrade script as root. Therefore, PostgreSQL sees you as the root user (which does not exist by default in PostgreSQL), instead of the irrd user you probably did create and give permissions in PostgreSQL.

So first step: run database_Upgrade as the same user that runs irrd.

**Comment by rubenskuhl** [comment]
> I think something else is happening here. I'm guessing that your database_url is configured so that PostgreSQL connects over a unix socket using peer authentication, and you are running the database_upgrade script as root. Therefore, PostgreSQL sees you as the root user (which does not exist by default in PostgreSQL), instead of the irrd user you probably did create and give permissions in PostgreSQL.
> 
> So first step: run database_Upgrade as the same user that runs irrd.

Actually, we ran database_upgrade as irrd... but we ended up finding the issue. PyPi never worked for us to compile IRRd, but the installation was trying to use PyPi instead of CPython when using pip3. Solution was to use python3 -m pip to force use CPython, and now everything works.
